import "./globals.css";
import { GraphQlProvider } from "./components/provider";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "@/app/components/header/header";
import { Footer } from "antd/es/layout/layout";
import { ThemeContextProvider } from "@/app/context/ThemeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Blog app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeContextProvider>
        <body className={inter.className}>
          <GraphQlProvider>
            <Header />
            {children}
            <Footer />
          </GraphQlProvider>
        </body>
      </ThemeContextProvider>
    </html>
  );
}
